services:
  api:
    image: ghcr.io/saleor/saleor:3.22
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - db
      - cache
      - jaeger
    volumes:
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
    environment:
      DASHBOARD_URL: https://dashboard.yourdomain.com/
      ALLOWED_HOSTS: api.yourdomain.com,localhost,127.0.0.1
      ALLOWED_CLIENT_HOSTS: store.yourdomain.com,localhost,127.0.0.1
      DATABASE_URL: postgres://saleor:saleor@db:5432/saleor
      PUBLIC_URL: https://api.yourdomain.com
    labels:
      - coolify.managed=true
      - coolify.routing.enabled=true
      - coolify.routing.entrypoint=websecure
      - coolify.routing.host=api.yourdomain.com
      - coolify.routing.port=8000

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:latest
    restart: unless-stopped
    environment:
      API_URL: https://api.yourdomain.com/graphql/
    labels:
      - coolify.managed=true
      - coolify.routing.enabled=true
      - coolify.routing.entrypoint=websecure
      - coolify.routing.host=dashboard.yourdomain.com
      - coolify.routing.port=80

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql:ro
    environment:
      POSTGRES_USER: saleor
      POSTGRES_PASSWORD: saleor

  cache:
    image: valkey/valkey:8.1-alpine
    restart: unless-stopped
    volumes:
      - saleor-cache:/data

  worker:
    image: ghcr.io/saleor/saleor:3.22
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    env_file:
      - common.env
      - backend.env
    depends_on:
      - cache
      - mailpit
    volumes:
      - saleor-media:/app/media

  jaeger:
    image: jaegertracing/jaeger
    restart: unless-stopped
    volumes:
      - type: tmpfs
        target: /tmp

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped

volumes:
  saleor-db:
  saleor-cache:
  saleor-media:
