
services:
  storefront:
    image: ghcr.io/saleor/storefront:latest
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_SALEOR_API_URL: https://api.example.com/graphql/
      NEXT_PUBLIC_STOREFRONT_URL: https://store.example.com
      NEXT_PUBLIC_DEFAULT_CHANNEL: default-channel
    labels:
      - coolify.managed=true
      - coolify.routing.enabled=true
      - coolify.routing.entrypoint=websecure
      - coolify.routing.host=store.example.com
      - coolify.routing.port=3000
